# Generated by Django 3.1.4 on 2020-12-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('github', models.CharField(max_length=500)),
                ('technology', models.CharField(max_length=500)),
            ],
        ),
    ]
