# Generated by Django 3.1.4 on 2020-12-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github',
            new_name='gitLink',
        ),
    ]
